openapi: 3.0.1
info:
  title: will be replaced
  description: This information will be replaced by the SpringFox config information
  version: 0.0.1
servers:
  - url: /
paths:
  /:
    get:
      tags:
        - root-controller
      summary: 'Returns the hal root entry point. [Authorization: Role: agency-admin]'
      operationId: getRoot
      responses:
        200:
          description: OK - successfull operation
          content:
            application/hal+json:
              schema:
                $ref: '#/components/schemas/RootDTO'
      security:
        - Bearer: [ ]
  /admin/agencies:
    get:
      tags:
        - admin-agency-controller
      summary: 'Returns the list of agencies by search query parameter. [Authorization: Role:
      agency-admin]'
      operationId: searchAgencies
      parameters:
        - name: q
          in: query
          description: The query parameter to search for
          schema:
            type: string
        - name: page
          in: query
          description: Number of page where to start in the query (1 = first page)
          required: true
          schema:
            type: integer
        - name: perPage
          in: query
          description: Number of items which are being returned
          required: true
          schema:
            type: integer
      responses:
        200:
          description: OK - successfull operation
          content:
            'application/hal+json':
              schema:
                $ref: '#/components/schemas/AgencyAdminSearchResultDTO'
        400:
          description: BAD REQUEST - invalid/incomplete request or body object
        500:
          description: INTERNAL SERVER ERROR - server encountered unexpected condition
      security:
        - Bearer: [ ]

components:
  schemas:
    RootDTO:
      type: object
      required:
        - _links
      properties:
        _links:
          $ref: '#/components/schemas/RootLinks'

    RootLinks:
      type: object
      required:
        - self
      properties:
        self:
          $ref: '#/components/schemas/halLink'
        agencies:
          $ref: '#/components/schemas/halLink'

    HalLink:
      type: object
      required:
        - href
      properties:
        href:
          type: string
        method:
          type: string
          enum: [ GET, POST, DELETE, PUT ]
        templated:
          type: boolean

    AgencyAdminSearchResultDTO:
      type: object
      properties:
        _embedded:
          type: array
          items:
            $ref: '#/components/schemas/AgencyAdminResponseDTO'
        _links:
          $ref: '#/components/schemas/SearchResultLinks'

    AgencyAdminResponseDTO:
      type: object
      properties:
        agencyId:
          type: integer
          format: int64
          example: "684"
        dioceseId:
          type: integer
          format: int64
          example: "684"
        name:
          type: string
          example: "Suchtberatung Freiburg"
        description:
          type: string
          example: "Our agency provides help for the following topics: Lorem ipsum.."
        postcode:
          type: string
          example: "79106"
        city:
          type: string
          example: "Bonn"
        teamAgency:
          type: boolean
          example: "false"
        offline:
          type: boolean
          example: "false"
        consultingType:
          type: integer
          example: "1"
        createDate:
          type: string
        updateDate:
          type: string
        deleteDate:
          type: string
        postCodeRanges:
          type: array
          items:
            $ref: '#/components/schemas/PostCodeRangeDTO'

    PostCodeRangeDTO:
      type: object
      properties:
        postcodeFrom:
          type: string
          example: "79106"
        postcodeTo:
          type: string
          example: "79106"

    SearchResultLinks:
      type: object
      required:
        - self
      properties:
        self:
          $ref: '#/components/schemas/halLink'
        next:
          $ref: '#/components/schemas/halLink'
        previous:
          $ref: '#/components/schemas/halLink'
        search:
          $ref: '#/components/schemas/halLink'

  securitySchemes:
    Bearer:
      type: apiKey
      name: Authorization
      in: header
